on:
  push:
    branches:
      - master
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v0.3.4                # 手动修改
          release_name: Release v0.3.4    # 手动修改
          body: |                         # 手动修改
            Changes in this Release
            - nothing
            - nothing
          draft: false
          prerelease: false

